### ISSUE TITLE
GitlabCI showing wrong build status.

### ISSUE THREAD

**Issue by gabriel-card** [marcells/node-build-monitor#49]
Hi!
I just caught a tiny problem in the GitlabCI support. As you're fetching for jobs (as the GitlabAPI v3 only supports a /builds/ route) and not pipelines (not supported in the GitlabAPI v3), if I'm running a pipeline with the last stage having multiple jobs running, the status of the pipeline will show up in the monitor as the status of the last completed job in the stage, instead of the status of the pipeline.

There are some alternatives to solve this issue, one of them is supporting GitlabAPI v4 (which I do not prefer solely because my company will not be updating Gitlab soon, and we're stuck with the v3 :P) and the other is simply making the code a little bit more complex. I don't know how complex you wish your code to be, so I'm forking the project and will be making some tests.

Just letting you know about this problem and hopefully having some insight from you.

PS: Sorry for my english, not my native language. If I've not been clear in any of my message, please feel free to say it and I'll try to explain with other words.

Cya!

**Comment by marcells** [comment]
Hi, I did not implement the GitLab service. ;-) Maybe @datakurre can help you.

**Comment by datakurre** [comment]
@gabriel-card Hi, you are correct that it's kinda broken now, but it still works well enough that I have not found time to upgrade it for the new API. Contributions are welcome.

The main difficulty in GitLab plugin was (at least at the time of writing) that each project had to be queried separately, which takes tile when you have hundreds if not thousands of projects to track. All that just to get the 16 latest builds. That makes the plugin a bit more complex than it should be, because it cannot query builds only when node-monitor asks for them, but it's querying builds all the time (with some delay to not choke GitLab).

**Comment by arunkumarsundaramurthy** [comment]
Looks like its still showing the wrong status.. Not sure of api v3.. but with v4 we can get the status of the pipeline.. also the status is not fetched at pipeline level.. its fetched at job level.. so multiple jobs are appearing on the monitor instead of one pipeline.. if no one is working on it, i can go ahead and fix this and give a PR..

**Comment by datakurre** [comment]
Please, do. I haven't had jne time to lookup the new apis yet.

**Comment by marcells** [comment]
Was the issue fixed with PR #53?

**Comment by datakurre** [comment]
I assume not. I recall that my initial implementation, before pipelines were implemented nor available through API, displayed one on-going build per branch (the one with last start date) and then the status of the last build – that's also why it still mostly shows the correct status. I don't see changes for that in #53.

I tried to look the new API docs, but still see no improvement for asking statuses of all pipelines on a GitLab host (currently it's quite costly to query possible build status for > 1k projects).

**Comment by marcells** [comment]
Hm, okay. So what will we do now with this issue? ;-)

**Comment by datakurre** [comment]
Wait for someone to have time to fix it :) I should have a day for stuff like this later this month (fingers crossed).

**Comment by datakurre** [comment]
@gabriel-card Is this still valid?

I had time to look into this and noticed that GitLab integration was rewritten recently so this behavior prorably have changed. Maybe even fixed.

Unfortunately, because the new integration is not sufficient for us, I could only fix this into my fork https://github.com/datakurre/node-build-monitor/tree/datakurre-custom and will stop monitoring the official version for now.

(We need to watch GitLab with 1k repositories with only about 20 in active development at time, so while seeing 20 active builds/failurs at time is sufficient, we need to be very careful how to poll those 1k repos properly to not DOS GitLab :+)

**Comment by gabriel-card** [comment]
@datakurre I think it's still an issue, but i'm not using it anymore.
A team from our company decided to build a monitor themselves, and we're using it since. Don't know if they made it opensource, I can ask monday though.

**Comment by datakurre** [comment]
@gabriel-card Ok. Thanks. Maybe this should be closed then until someone can reproduce.

We are happy with node-build-monitor. It was very easy to extend. Our only issues have been due to GitLab CE’s API making it difficult to track builds for all the projects on it, but we are happy with our current fork now.

**Comment by marcells** [comment]
@gabriel-card Sorry to hear that node-build-monitor wasn't suitable for you.

@datakurre Does it make sense to reintegrate your changes into the main project? Are there any disadvantages, beside complexity, or major changes necessary?

**Comment by gabriel-card** [comment]
@marcells Sorry if it came out that way, by no means it wasn't suitable. We were actually using it despite this minor problem. We did not change because of that, we just wanted to support their work. It was done as a hackaton project, and we have this thing that we always try to use everything we make out of those hackatons.
This is a nice project and nicely build, keep it up! =)

**Comment by Esysc** [comment]
I agree, this is a great project I was looking  for a long time . Then, if somebody needs custom hack ,  it doesn't  mean the project lacks some features,  actually some environments are not standard and we need to adapt.

**Comment by datakurre** [comment]
@marcells The current rewritten GitLab CI integration is simper, cleaner and therefore easier to maintain than my version, so I actually recommend keeping it. I suppose it works well for gitlab.com and small installations. But if someone reports performance issues with that, then you can ping me. It's well possible that meanwhile GitLab creates better API for making it easier to find "global" new build jobs from GitLab installation...

**Comment by marcells** [comment]
Allright. Thank you for your information. I'll close this issue now.
